apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - db/
  - default/
  # - infra/
  - monitoring/
  - network/
  - security/
  - storage/
  - testing/
